import uuid
import datetime
from typing import Dict, Any
from sqlalchemy.orm import Session
from models import WorkflowNode

class BusinessRulesEngine:
    """
    BUSINESS RULES ENGINE (BRE) CORE RUNTIME ENGINE
    Pillar: Logic-as-Data. Implements a parameter-driven computation matrix.
    Completely domain-agnostic; interprets rulesets generated by 'The Canvas OS'.
    """
    def __init__(self, rule_manifest_matrix: Dict[str, Any]):
        self.rule_id = rule_manifest_matrix.get("rule_id", "UNKNOWN")
        self.version = rule_manifest_matrix.get("version", "1.0.0")
        self.steps = rule_manifest_matrix.get("calculation_steps", [])

    def execute_logic(self, runtime_context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Executes a sequence of mathematical operations or conditional filters
        on an incoming data stream based purely on the loaded ruleset data.
        """
        execution_logs = []
        
        for step in self.steps:
            op = step.get("operation")
            src = step.get("source_field")
            tgt = step.get("target_field")
            param_raw = step.get("parameter", "0.0")
            
            if op == "SYMBOLIC_FORMULA":
                formula_str = str(param_raw)
                try:
                    eval_context = {k: float(v) for k, v in runtime_context.items() if isinstance(v, (int, float))}
                    calculated_val = eval(formula_str, {"__builtins__": None}, eval_context)
                    runtime_context[tgt] = calculated_val
                    execution_logs.append(f"Evaluated formula [{formula_str}]. Result stored to {tgt} = {runtime_context[tgt]}")
                except Exception as eval_err:
                    runtime_context[tgt] = 0.0
                    execution_logs.append(f"Formula evaluation bypassed or halted: {str(eval_err)}")
            else:
                param = float(param_raw) if str(param_raw).replace('.', '', 1).isdigit() else 0.0
                val = runtime_context.get(src, 0.0)
                if op == "PERCENTAGE_SPLIT":
                    runtime_context[tgt] = val * param
                    execution_logs.append(f"Applied {param} split to {src}. Resulting target {tgt} = {runtime_context[tgt]}")
                elif op == "CAP_LIMIT":
                    runtime_context[tgt] = min(val, param)
                    execution_logs.append(f"Enforced ceiling cap of {param} on {src}. Output = {runtime_context[tgt]}")
                elif op == "NET_BALANCE":
                    reducer_value = runtime_context.get(step.get("reducer_field"), 0.0)
                    calculated_value = val - reducer_value
                    runtime_context[tgt] = calculated_value
                    execution_logs.append(f"Subtracted {step.get('reducer_field')} from {src}. Final balance = {calculated_value}")

        return {"bre_metadata": {"rule_id": self.rule_id, "version": self.version, "execution_status": "COMPLETED_SUCCESSFULLY"}, "final_calculated_state": runtime_context, "audit_trail_logs": execution_logs}

def process_workflow_node(payload: Dict[str, Any], db: Session) -> Dict[str, Any]:
    """
    Handles WORKFLOW_NODE_COMMIT manifests.
    Maps incoming step attributes, node IDs, SLAs, and rule maps directly to the database transaction framework.
    """
    node_id = payload.get("node_id", f"NODE-{uuid.uuid4().hex[:8].upper()}")
    workflow_id = payload.get("workflow_id")
    
    if not workflow_id:
        return {"status": "error", "message": "workflow_id is required"}

    new_node = WorkflowNode(
        node_id=node_id,
        workflow_id=workflow_id,
        sequence_number=payload.get("sequence_number", 1),
        node_title=payload.get("node_title", "Untitled Node"),
        node_code=payload.get("node_code", "UNKNOWN_CODE"),
        canvas_x_position=payload.get("canvas_x_position", 0),
        canvas_y_position=payload.get("canvas_y_position", 0),
        rules_applied=payload.get("rules_applied", []),
        calculations=payload.get("calculations", []),
        api_triggers=payload.get("api_triggers", []),
        events_broadcast=payload.get("events_broadcast", []),
        sla_days=payload.get("sla_days", 1),
        sla_anchor_field=payload.get("sla_anchor_field", None),
        screen_template=payload.get("screen_template", None),
        created_at=datetime.datetime.utcnow().isoformat()
    )
    
    try:
        db.add(new_node)
        db.commit()
        db.refresh(new_node)
        return {"status": "success", "node_id": node_id, "message": "Workflow node committed successfully"}
    except Exception as e:
        db.rollback()
        return {"status": "error", "message": str(e)}