import json
from typing import Dict, Any, List

class BusinessRulesEngine:
    """
    BUSINESS RULES ENGINE (BRE) CORE RUNTIME ENGINE
    Pillar: Logic-as-Data. Implements a parameter-driven computation matrix.
    Completely domain-agnostic; interprets rulesets generated by 'The Canvas OS'.
    """
    def __init__(self, rule_manifest_matrix: Dict[str, Any]):
        # This simulates loading the versioned policy configuration from the DB
        self.rule_id = rule_manifest_matrix.get("rule_id")
        self.version = rule_manifest_matrix.get("version")
        self.steps = rule_manifest_matrix.get("calculation_steps", [])

    def execute_logic(self, canonical_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Executes a sequence of mathematical operations or conditional filters
        on an incoming data stream based purely on the loaded ruleset data.
        """
        runtime_context = canonical_data.get("mapped_fields", {}).copy()
        execution_logs = []
        
        print(f"Executing Ruleset: {self.rule_id} ({self.version})")
        
        # Sequentially evaluate each node/step configured on the Canvas
        for step in self.steps:
            step_name = step.get("step_name")
            operation = step.get("operation") # e.g., MULTIPLY, PERCENTAGE_SPLIT, ALLOCATE
            source_field = step.get("source_field")
            target_field = step.get("target_field")
            parameter = step.get("parameter", 0.0)
            
            # Extract current running value from the data payload
            current_value = runtime_context.get(source_field, 0.0)
            
            if operation == "PERCENTAGE_SPLIT":
                # Compute a fractional allocation (e.g., managing tax cuts or fee shares)
                calculated_value = current_value * float(parameter)
                runtime_context[target_field] = calculated_value
                execution_logs.append(f"[{step_name}] Applied {parameter} split to {source_field}. Resulting target {target_field} = {calculated_value}")
                
            elif operation == "CAP_LIMIT":
                # Enforce a financial ceiling check limit
                calculated_value = min(current_value, float(parameter))
                runtime_context[target_field] = calculated_value
                execution_logs.append(f"[{step_name}] Enforced ceiling cap of {parameter} on {source_field}. Output = {calculated_value}")
                
            elif operation == "NET_BALANCE":
                # Basic differential logic block
                reducer_value = runtime_context.get(step.get("reducer_field"), 0.0)
                calculated_value = current_value - reducer_value
                runtime_context[target_field] = calculated_value
                execution_logs.append(f"[{step_name}] Subtracted {step.get('reducer_field')} from {source_field}. Final balance = {calculated_value}")

        return {
            "bre_metadata": {
                "rule_id": self.rule_id,
                "version": self.version,
                "execution_status": "COMPLETED_SUCCESSFULLY"
            },
            "final_calculated_state": runtime_context,
            "audit_trail_logs": execution_logs
        }
