from sqlalchemy.orm import Session
from typing import Dict, Any, List, Optional
import models
import json
import asyncio
import os
from services.calculation_engine import CalculationEngine
from services.business_rule_engine import BusinessRuleEngine
from services.data_masking import DataMaskingService
from event_bus import global_event_bus, SystemEvent
from services.integration_dispatcher import IntegrationDispatcher
from services.asset_cache import AssetCache

from services.redis_middleware import redis_client, rate_limit_script

class WorkflowExecutor:
    """
    Core engine to execute a defined workflow blueprint (Layer 4: Deterministic Execution).
    
    This service is the heart of the execution layer. It processes an input payload 
    by traversing the workflow's graph of nodes and edges, executing associated 
    rules, calculations, and API calls at each step. It is designed to be domain-agnostic,
    interpreting the JSON manifests generated by the visual studios.

    Crucially, it also acts as a central enforcement point for Layer 6 Governance rules,
    such as data masking, currency consistency, and financial ledger validation.
    """

    def __init__(self, db: Session, workflow_id: str):
        """
        Initializes the executor for a specific workflow run.
        """
        self.db = db
        self.workflow = db.query(models.WorkflowConfiguration).filter(
            models.WorkflowConfiguration.workflow_id == workflow_id
        ).first()
        if not self.workflow:
            raise ValueError(f"Workflow with ID '{workflow_id}' not found.")
        
        # Initialize the data masking service in alignment with architecture Layer 6
        self.masking_service = DataMaskingService()
        
        # Load centralized asset cache for O(1) in-memory lookups
        cache = AssetCache(db)
        self.pii_field_properties = cache.pii_field_properties

        # Pre-process nodes and edges for efficient lookups
        self.nodes_by_id = {node.node_id: node for node in self.workflow.nodes}
        self.edges_from_node = {}
        for edge in self.workflow.edges:
            if edge.source_node_id not in self.edges_from_node:
                self.edges_from_node[edge.source_node_id] = []
            self.edges_from_node[edge.source_node_id].append(edge)
            
        self.api_configs_by_id = cache.api_configs_by_id
        self.formulas_by_token_code = cache.formulas_by_token_code
        self.composite_formulas_by_token_code = cache.composite_formulas_by_token_code
        self.rule_sets_by_token_code = cache.rule_sets_by_token_code
        self.recon_templates_by_id = cache.recon_templates_by_id
            
        # Initialize unified outbound integration dispatcher
        self.integration_dispatcher = IntegrationDispatcher(self.api_configs_by_id)

        self.execution_trace = []

    def _validate_currency_consistency(self, context: Dict[str, Any]):
        """
        Layer 4 Guardrail: Enforces the Currency-Aware Calculation Safe-Wrapper.
        Prevents mathematical operations on mixed currencies.
        """
        currencies_found = set()
        # Heuristic: find amount fields and look for their corresponding currency fields.
        for key, value in context.items():
            if "amount" in key.lower() and isinstance(value, (int, float)):
                currency_key = f"{key}_currency"
                if currency_key in context:
                    currencies_found.add(context[currency_key])
        
        if len(currencies_found) > 1:
            raise ValueError(f"Cross-currency operation detected ({', '.join(currencies_found)}). An FX Oracle middleware call is required before calculation. Halting path.")
        
        if len(currencies_found) == 1:
            self.execution_trace.append(f"✓ Currency Consistency Check Passed. All amounts are in {list(currencies_found)[0]}.")

    def _apply_localized_compliance_rules(self, node: models.WorkflowNode, context: Dict[str, Any]):
        """
        Layer 6 Guardrail: Applies Dynamic Country-Specific Compliance Bundles.
        """
        country_code = context.get("country_code", "DEFAULT").upper()
        amount = context.get("transaction_amount", 0.0)

        if node.node_code in ["POST_LEDGER", "SETTLE"]:
            self.execution_trace.append(f"Applying localized compliance rules for jurisdiction: {country_code}")
            if country_code == "US" and amount > 10000:
                self.execution_trace.append("[COMPLIANCE_EVENT] Triggering US AML reporting sub-routine (FinCEN CTR).")
            elif country_code == "IN" and context.get("is_cross_border", False):
                 self.execution_trace.append("[COMPLIANCE_EVENT] Triggering India cross-border reporting sub-routine (RBI).")

    def _validate_double_entry_ledger(self, node: models.WorkflowNode, context: Dict[str, Any]):
        """
        Layer 6 Guardrail: Enforces the Double-Entry Ledger Guardrail.
        This is a hardcoded constraint for financial movement nodes.
        """
        self.execution_trace.append(f"Applying Double-Entry Ledger Guardrail for node '{node.node_title}'.")
        
        # Assume the transaction legs are returned by one of the node's API triggers
        transaction_legs = []
        if 'api_responses' in context:
            for api_response in context['api_responses'].values():
                if isinstance(api_response, dict) and 'legs' in api_response:
                    transaction_legs = api_response.get('legs', [])
                    break # Found the legs, stop searching
        
        if not transaction_legs:
            raise ValueError("Financial movement node did not produce a transaction packet with 'legs'. Execution halted.")

        total_debits = 0.0
        total_credits = 0.0

        for leg in transaction_legs:
            leg_type = leg.get('type', '').upper()
            amount = float(leg.get('amount', 0.0))
            if leg_type == 'DEBIT':
                total_debits += amount
            elif leg_type == 'CREDIT':
                total_credits += amount
        
        if abs(total_debits - total_credits) > 0.001:
            raise ValueError(f"Imbalanced transaction. Debits ({total_debits}) do not equal Credits ({total_credits}).")

        self.execution_trace.append(f"✓ Double-Entry Guardrail Passed. Debits ({total_debits}) = Credits ({total_credits}).")

    def _evaluate_edge_condition(self, condition: Optional[Dict[str, Any]], context: Dict[str, Any]) -> bool:
        """
        Safely evaluates a structured JSON condition object against the current context.
        Returns True if the condition passes or if the condition is empty/invalid.
        """
        if not condition:
            return True # An edge with no condition is considered a default path

        try:
            condition_type = condition.get("type", "SIMPLE").upper()

            if condition_type == "BUSINESS_RULE":
                rule_token = condition.get("token_code")
                if not rule_token: return False
                
                rule_set_model = self.rule_sets_by_token_code.get(rule_token)
                if not rule_set_model:
                    self.execution_trace.append(f"[WARN] Edge condition rule '{rule_token}' not found. Path disabled.")
                    return False
                
                bre = BusinessRuleEngine(rule_set_model.definition, calculation_engine=None)
                rule_passed, _, _ = bre.execute(runtime_context=context)
                return rule_passed
            else: # Default to simple legacy condition for backward compatibility
                field = condition.get("field")
                operator = condition.get("operator")
                value = condition.get("value")
                context_value = context.get(field)

                if operator == "==": return context_value == value
                elif operator == "!=": return context_value != value
                # Add other simple operators as needed...
                return False
        except Exception as e:
            self.execution_trace.append(f"[WARN] Could not evaluate edge condition due to error: {e}")
            return False # Fail-safe for malformed conditions
        
        # New logic for event matching
        if condition_type == "EVENT_MATCH":
            event_type_to_match = condition.get("event_type")
            payload_to_match = condition.get("match_payload", {})
            
            for event in self.events_this_step:
                if event["event_type"] == event_type_to_match:
                    # Simple key-value check in payload
                    match = all(event["payload"].get(k) == v for k, v in payload_to_match.items())
                    if match:
                        self.execution_trace.append(f"  -> Edge condition met by event: {event_type_to_match}")
                        return True
            return False

        return True # Default pass if condition is not EVENT_MATCH and didn't fail before

    def _execute_node_actions(self, node: models.WorkflowNode, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Executes the actions defined for a single node (rules, calculations, API calls).
        """
        self.execution_trace.append(f"Entering Node: '{node.node_title}' (Seq: {node.sequence_number})")

        self.events_this_step = [] # Initialize list to hold events generated in this step
        has_calcs = getattr(node, "calculations", False)
        if not has_calcs and node.orchestration_steps:
            for step in node.orchestration_steps:
                if isinstance(step, dict) and step.get("step_type") == "CALCULATION":
                    has_calcs = True
                    break
        if has_calcs:
            self._validate_currency_consistency(context)

        # 1. Execute the unified orchestration steps for this node
        if node.orchestration_steps:
            sorted_steps = sorted(node.orchestration_steps, key=lambda s: s.get('sequence_number', 99))

            for step in sorted_steps:
                # --- Conditional Invocation Check ---
                should_invoke = True
                rule_token = step.get("invocation_rule_token")
                if rule_token:
                    self.execution_trace.append(f"Evaluating invocation rule '{rule_token}' for step.")
                    rule_set_model = self.rule_sets_by_token_code.get(rule_token)
                    if rule_set_model:
                        # For simple conditional checks, we don't need to pass a full calc engine
                        bre = BusinessRuleEngine(rule_set_model.definition, calculation_engine=None)
                        rule_passed, _, rule_logs = bre.execute(runtime_context=context)
                        self.execution_trace.extend(rule_logs)
                        if not rule_passed:
                            should_invoke = False
                            self.execution_trace.append(f"  -> Invocation rule evaluated to false. Skipping step.")
                    else:
                        should_invoke = False
                        self.execution_trace.append(f"  -> [WARN] Invocation rule '{rule_token}' not found. Skipping step.")

                if not should_invoke:
                    continue
                
                # --- Execute Step based on Type ---
                step_type = step.get("step_type")
                target_token = step.get("target_token")
                target_event_type = step.get("target_event_type")

                if step_type == "BUSINESS_RULE":
                    self.execution_trace.append(f"Executing step: BUSINESS_RULE '{target_token}'")
                    rule_set_model = self.rule_sets_by_token_code.get(target_token)
                    if not rule_set_model:
                        self.execution_trace.append(f"[WARN] Business Rule Set '{target_token}' not found. Skipping.")
                        continue
                    
                    # The BRE needs the CE to execute calculation actions
                    calc_engine_for_bre = CalculationEngine(formula_library=self.formulas_by_token_code)
                    bre = BusinessRuleEngine(rule_set_model.definition, calc_engine_for_bre)
                    _, context, logs = bre.execute(runtime_context=context)
                    self.execution_trace.extend(logs)

                elif step_type == "API_CALL":
                    self.execution_trace.append(f"Executing step: API_CALL '{target_token}'")
                    
                    success, api_logs, api_events = self.integration_dispatcher.execute_api_call(
                        api_id=target_token,
                        context=context,
                        masking_service=self.masking_service,
                        pii_field_properties=self.pii_field_properties
                    )
                    self.execution_trace.extend(api_logs)
                    self.events_this_step.extend(api_events)

                elif step_type == "CALCULATION":
                    self.execution_trace.append(f"Executing step: CALCULATION '{target_token}'")
                    calc_engine = CalculationEngine(formula_library=self.formulas_by_token_code)
                    
                    # Handle both simple and composite formulas
                    if target_token in self.formulas_by_token_code:
                        calc_result = calc_engine.execute_formula_by_token(target_token, context)
                        context = calc_result["final_context"]
                        self.execution_trace.extend(calc_result["logs"])
                    elif target_token in self.composite_formulas_by_token_code:
                        composite_asset = self.composite_formulas_by_token_code[target_token]
                        sorted_comp_steps = sorted(composite_asset.steps, key=lambda s: s.sequence_number)
                        for comp_step in sorted_comp_steps:
                            calc_result = calc_engine.execute_formula_by_token(comp_step.formula_token_code, context)
                            context = calc_result["final_context"] # Ensure context is updated for the next step in the composite
                            self.execution_trace.extend(calc_result["logs"])
                    else:
                        self.execution_trace.append(f"[WARN] Calculation asset with token '{target_token}' not found. Skipping.")
                
                elif step_type == "EVENT_BROADCAST":
                    if not target_event_type:
                        self.execution_trace.append(f"[WARN] EVENT_BROADCAST step is missing a 'target_event_type'. Skipping.")
                        continue
                    self.execution_trace.append(f"Executing step: EVENT_BROADCAST for event type '{target_event_type}'")
                    
                    trace_depth = context.get("__trace_depth__", 0) + 1
                    correlation_id = context.get("__correlation_id__", f"CORR-{uuid.uuid4().hex[:12]}")
                    asyncio.run(global_event_bus.broadcast(SystemEvent(
                        event_type=target_event_type,
                        source_context=f"OrchestrationStep:{node.node_id}",
                        payload=context, # Broadcast the current context as the payload
                        trace_depth=trace_depth,
                        correlation_id=correlation_id
                    ), db=self.db))

                elif step_type == "SUB_WORKFLOW":
                    if not target_token:
                        self.execution_trace.append(f"[WARN] SUB_WORKFLOW step is missing a 'target_token' (workflow_id). Skipping.")
                        continue
                    self.execution_trace.append(f"Executing step: SUB_WORKFLOW '{target_token}'")
                    
                    try:
                        # Instantiate a new executor for the nested sub-workflow
                        sub_executor = WorkflowExecutor(db=self.db, workflow_id=target_token)
                        
                        # --- GAP 3: Input Scope Isolation ---
                        child_input = context.copy()
                        if sub_executor.workflow.input_schema:
                            self.execution_trace.append(f"Applying strict input schema filter for Sub-Workflow.")
                            child_input = {k: context.get(k) for k in sub_executor.workflow.input_schema}

                        # --- GAP 1: Intelligent Sub-Workflow Resumption Check ---
                        child_instance_key = f"__child_instance_{target_token}_{step.get('sequence_number')}__"
                        existing_child_id = context.get(child_instance_key)
                        
                        if existing_child_id:
                            child_instance = self.db.query(models.WorkflowExecutionInstance).filter(models.WorkflowExecutionInstance.instance_id == existing_child_id, models.WorkflowExecutionInstance.status == "PAUSED").first()
                            if child_instance:
                                self.execution_trace.append(f"Resuming existing Sub-Workflow '{target_token}' (Instance: {existing_child_id})")
                                sub_result = sub_executor.execute(initial_payload=child_input, resume_from_node_id=child_instance.current_node_id, resume_trace=child_instance.execution_trace)
                            else:
                                sub_result = sub_executor.execute(initial_payload=child_input)
                        else:
                            sub_result = sub_executor.execute(initial_payload=child_input)
                        
                        # Merge the execution traces for a unified audit log
                        self.execution_trace.append(f"--- Sub-Workflow '{target_token}' Trace Start ---")
                        self.execution_trace.extend(sub_result.get("trace", []))
                        self.execution_trace.append(f"--- Sub-Workflow '{target_token}' Trace End ---")
                        
                        if sub_result.get("status") == "PAUSED":
                            self.execution_trace.append(f"Sub-workflow '{target_token}' paused. Cascading pause to parent.")
                            # Inject a special signal into the context so the main execute loop knows to pause
                            context["__sub_workflow_paused__"] = sub_result
                            context[child_instance_key] = sub_result.get("instance_id") # Store for safe resumption!
                        elif sub_result.get("status") == "FAILED":
                            raise ValueError(f"Nested Sub-workflow '{target_token}' failed.")
                        else:
                            # --- GAP 3: Output Scope Isolation ---
                            if child_instance_key in context: del context[child_instance_key]
                            child_output = sub_result.get("final_context", {})
                            if sub_executor.workflow.output_schema:
                                self.execution_trace.append(f"Applying strict output schema filter from Sub-Workflow.")
                                child_output = {k: child_output.get(k) for k in sub_executor.workflow.output_schema if k in child_output}
                            context.update(child_output)
                    except Exception as e:
                        self.execution_trace.append(f"[ERROR] Sub-workflow execution failed: {str(e)}")
                        raise ValueError(f"Sub-Workflow Engine Failure: {str(e)}")

                elif step_type == "GENERATE_DOCUMENT":
                    # --- GAP 2: Outbound Reverse Mapping to generate structured file payloads ---
                    mapper_id = target_token
                    self.execution_trace.append(f"Executing step: GENERATE_DOCUMENT using mapper '{mapper_id}'")
                    mapper = self.db.query(models.PayloadMapperBlueprint).filter(models.PayloadMapperBlueprint.mapper_id == mapper_id).first()
                    
                    if not mapper or mapper.mapping_direction != "OUTBOUND":
                        self.execution_trace.append(f"[WARN] Valid OUTBOUND Mapper '{mapper_id}' not found. Skipping.")
                        continue
                    
                    generated_payload = {}
                    for mapping in mapper.mappings:
                        iso_val = context.get(mapping.target_iso_field, mapping.default_value)
                        if mapping.calculation_token_code:
                             calc_engine = CalculationEngine(formula_library=self.formulas_by_token_code)
                             calc_res = calc_engine.execute_formula_by_token(mapping.calculation_token_code, context)
                             iso_val = calc_res["final_context"].get(mapping.target_iso_field, iso_val)
                             self.execution_trace.extend(calc_res["logs"])
                        generated_payload[mapping.source_extracted_field] = iso_val
                        
                    if "generated_documents" not in context:
                        context["generated_documents"] = {}
                    context["generated_documents"][mapper_id] = generated_payload
                    self.execution_trace.append(f"Successfully generated outbound payload mapping for '{mapper_id}'.")

                elif step_type == "RECONCILIATION":
                    self.execution_trace.append(f"Executing step: RECONCILIATION '{target_token}'")
                    from routers.reconciliation_engine import ReconciliationEngine
                    
                    template = self.recon_templates_by_id.get(target_token)
                    if not template:
                        self.execution_trace.append(f"[WARN] Reconciliation Template '{target_token}' not found. Skipping.")
                        continue
                        
                    source_data = context.get(template.source_dataset_name, [])
                    target_data = context.get(template.target_dataset_name, [])
                    
                    if not isinstance(source_data, list) or not isinstance(target_data, list):
                        self.execution_trace.append(f"[ERROR] Source or Target datasets are not lists. Skipping.")
                        continue
                        
                    # Pre-process datasets with Calculation Engine
                    calc_engine = CalculationEngine(formula_library=self.formulas_by_token_code)
                    for rule in template.matching_rules:
                        calc_token = rule.get("pre_calculation_token")
                        if calc_token:
                            for row in source_data:
                                calc_result = calc_engine.execute_formula_by_token(calc_token, row)
                                row.update(calc_result["final_context"])
                                
                    recon_engine = ReconciliationEngine()
                    try:
                        recon_result = recon_engine.match_sets(source_data, target_data, template.matching_rules)
                        context["reconciliation_results"] = recon_result
                        self.execution_trace.append(f"Reconciliation '{template.reconciliation_name}' complete. Matched: {len(recon_result['matched'])}, Variances: {len(recon_result['variance'])}.")
                        
                        # Layer 6 Governance: If there are variances or unmatched, halt workflow & broadcast
                        if len(recon_result['variance']) > 0 or len(recon_result['unmatched_a']) > 0 or len(recon_result['unmatched_b']) > 0:
                            error_msg = f"Reconciliation '{template.reconciliation_name}' failed with {len(recon_result['variance'])} variances, {len(recon_result['unmatched_a'])} unmatched source, and {len(recon_result['unmatched_b'])} unmatched target records."
                            self.execution_trace.append(f"[RECON_ERROR] {error_msg}")
                            raise ValueError(error_msg)
                    except Exception as e:
                        self.execution_trace.append(f"[ERROR] Reconciliation execution failed: {str(e)}")
                        raise ValueError(f"Reconciliation Engine Failure: {str(e)}")

        # --- Final Layer 6 Governance Checks for Financial Nodes ---
        # After all actions, apply hardcoded governance guardrails.
        if node.node_code in ["POST_LEDGER", "SETTLE"]:
            # Layer 6 Guardrail: Invariant State Verification Gate.
            # All financial state changes for this node are executed within a single,
            # atomic database transaction. A failure will trigger a hard rollback.
            try:
                with self.db.begin():
                    self.execution_trace.append("Entering Invariant State Verification Gate for financial node.")
                    # This implements the "Double-Entry Ledger Guardrail" specification.
                    self._validate_double_entry_ledger(node, context)
                    self._apply_localized_compliance_rules(node, context)
                    # If we reach here, the block was successful and will be committed.
                    self.execution_trace.append("✓ Invariant State Verification Passed. Transaction block will be committed.")
            except ValueError as e:
                # The 'with' block handles the rollback automatically on exception.
                self.execution_trace.append(f"[FATAL_INVARIANT_ERROR] State verification failed: {str(e)}. Transaction block rolled back.")
                # Re-raise the exception to halt this execution path.
                raise e

        return context

    def execute(self, initial_payload: Dict[str, Any], resume_from_node_id: str = None, resume_trace: list = None) -> Dict[str, Any]:
        """
        Runs the entire workflow from start to finish by traversing the graph.

        This is the main entry point for the executor. It takes an initial data payload
        and processes it through the workflow graph in a breadth-first manner, supporting
        both conditional branching and parallel path execution (forks/joins).

        Args:
            initial_payload: A dictionary representing the initial data for the workflow.

        Returns:
            A dictionary containing the final status, the final (masked) context, 
            and a detailed execution trace.
        """
        if not self.nodes_by_id:
            return {"status": "FAILED", "message": "Workflow has no nodes to execute.", "trace": []}

        current_context = initial_payload.copy()
        masked_context_for_log = self.masking_service.mask_pii_data(current_context, self.pii_field_properties)

        self.execution_trace.append(f"Starting execution for workflow: {self.workflow.workflow_name}")
        self.execution_trace.append(f"Initial Payload (Masked): {masked_context_for_log}")

        is_resume_iteration = False
        if resume_from_node_id:
            self.execution_trace = resume_trace or []
            self.execution_trace.append(f"--- Resuming execution from node: {resume_from_node_id} ---")
            
            if resume_from_node_id in self.nodes_by_id:
                active_nodes = [self.nodes_by_id[resume_from_node_id]]
                is_resume_iteration = True
            else:
                return {"status": "FAILED", "message": f"Resumed node {resume_from_node_id} not found.", "trace": self.execution_trace}
        else:
            try:
                start_node = sorted(self.workflow.nodes, key=lambda n: n.sequence_number)[0]
            except IndexError:
                return {"status": "FAILED", "message": "Cannot find a starting node.", "trace": self.execution_trace}
            active_nodes = [start_node]
            
        max_steps = len(self.nodes_by_id) * 2 + 5  # Increased safety buffer for forks/joins
        step_count = 0

        while active_nodes and step_count < max_steps:
            step_count += 1
            self.execution_trace.append(f"--- Step {step_count} ---")
            
            next_step_nodes = []
            # Use a set to handle multiple paths converging on the same node in the next step (fan-in)
            next_step_node_ids = set()

            for node in active_nodes:
                # --- LAYER 4 GOVERNANCE: DOCUMENT PREREQUISITES CHECKLIST ---
                if node.required_documents:
                    missing_docs = []
                    for doc_req in node.required_documents:
                        if isinstance(doc_req, str):
                            if doc_req not in current_context:
                                missing_docs.append(doc_req)
                        elif isinstance(doc_req, dict) and doc_req.get("is_mandatory", True):
                            if doc_req.get("document_name") not in current_context:
                                missing_docs.append(doc_req.get("document_name"))
                    if missing_docs:
                        self.execution_trace.append(f"Pausing execution at node '{node.node_title}'. Missing required documents: {missing_docs}")
                        import uuid
                        import datetime
                        
                        instance_id = f"WFI-{uuid.uuid4().hex[:12].upper()}"
                        instance = models.WorkflowExecutionInstance(
                            instance_id=instance_id,
                            workflow_id=self.workflow.workflow_id,
                            current_node_id=node.node_id,
                            status="PAUSED",
                            current_context=current_context, # Save raw context to preserve fields for resumption
                            execution_trace=self.execution_trace,
                            created_at=datetime.datetime.utcnow().isoformat()
                        )
                        self.db.add(instance)
                        self.db.commit()
                        
                        return {"status": "PAUSED", "workflow_id": self.workflow.workflow_id, "instance_id": instance_id, "trace": self.execution_trace, "missing_documents": missing_docs}

                if node.node_code == "HUMAN_APPROVAL":
                    if is_resume_iteration and node.node_id == resume_from_node_id:
                        self.execution_trace.append(f"Human approval confirmed for node '{node.node_title}'. Proceeding.")
                    else:
                        self.execution_trace.append(f"Pausing execution at node '{node.node_title}' for human approval.")
                        import uuid
                        import datetime
                        
                        instance_id = f"WFI-{uuid.uuid4().hex[:12].upper()}"
                        instance = models.WorkflowExecutionInstance(
                            instance_id=instance_id,
                            workflow_id=self.workflow.workflow_id,
                            current_node_id=node.node_id,
                            status="PAUSED",
                            current_context=current_context,
                            execution_trace=self.execution_trace,
                            created_at=datetime.datetime.utcnow().isoformat()
                        )
                        self.db.add(instance)
                        self.db.commit()
                        
                        return {"status": "PAUSED", "workflow_id": self.workflow.workflow_id, "instance_id": instance_id, "trace": self.execution_trace}

                try:
                    # Execute the node's primary actions, including governance checks
                    current_context = self._execute_node_actions(node, current_context)
                    
                    # --- LAYER 4: RECURSIVE SUB-WORKFLOW PAUSE BUBBLING ---
                    if "__sub_workflow_paused__" in current_context:
                        sub_result = current_context.pop("__sub_workflow_paused__")
                        self.execution_trace.append(f"Pausing execution at parent node '{node.node_title}' due to paused nested sub-workflow.")
                        import uuid
                        import datetime
                        
                        instance_id = f"WFI-{uuid.uuid4().hex[:12].upper()}"
                        
                        # Tie the child instance to this parent instance in the database
                        child_instance_id = sub_result.get("instance_id")
                        if child_instance_id:
                            child_instance = self.db.query(models.WorkflowExecutionInstance).filter(models.WorkflowExecutionInstance.instance_id == child_instance_id).first()
                            if child_instance:
                                child_instance.parent_instance_id = instance_id
                                self.db.commit()

                        instance = models.WorkflowExecutionInstance(
                            instance_id=instance_id,
                            workflow_id=self.workflow.workflow_id,
                            current_node_id=node.node_id,
                            status="PAUSED",
                            current_context=current_context, # Save raw context to preserve fields for resumption
                            execution_trace=self.execution_trace,
                            created_at=datetime.datetime.utcnow().isoformat()
                        )
                        self.db.add(instance)
                        self.db.commit()
                        
                        return {"status": "PAUSED", "workflow_id": self.workflow.workflow_id, "instance_id": instance_id, "trace": self.execution_trace, "missing_documents": sub_result.get("missing_documents")}

                except ValueError as e:
                    self.execution_trace.append(f"[FATAL_GOVERNANCE_ERROR] Path terminated at node '{node.node_title}': {str(e)}")
                    # This path is now dead, so we just 'continue' to the next active_node in the current step
                    continue

                outgoing_edges = self.edges_from_node.get(node.node_id, [])
                if not outgoing_edges:
                    self.execution_trace.append(f"Execution path finished at terminal node: '{node.node_title}'")
                    continue

                found_a_path = False
                # Evaluate all outgoing edges to handle forks (fan-out)
                for edge in outgoing_edges:
                    if self._evaluate_edge_condition(edge.edge_condition, current_context):
                        found_a_path = True
                        next_node_id = edge.target_node_id
                        
                        if next_node_id in self.nodes_by_id and next_node_id not in next_step_node_ids:
                            next_step_node_ids.add(next_node_id)
                            next_step_nodes.append(self.nodes_by_id[next_node_id])
                            self.execution_trace.append(f"Condition passed for edge from '{node.node_title}' to '{self.nodes_by_id[next_node_id].node_title}'. Queuing for next step.")
                
                if not found_a_path:
                    self.execution_trace.append(f"No valid conditional path found from node '{node.node_title}'. This path terminates here.")

            active_nodes = next_step_nodes
            is_resume_iteration = False # Reset after first iteration
        
        if step_count >= max_steps:
            self.execution_trace.append("[ERROR] Execution halted. Maximum step count exceeded, possible infinite loop detected.")
            
            # --- BROADCAST FAILURE EVENT ---
            trace_depth = current_context.get("__trace_depth__", 0) + 1
            correlation_id = current_context.get("__correlation_id__", f"CORR-{uuid.uuid4().hex[:12]}")
            asyncio.run(global_event_bus.broadcast(SystemEvent(
                event_type="WORKFLOW_FAILED",
                source_context=f"WorkflowExecutor:{self.workflow.workflow_id}",
                payload={"reason": "Max steps exceeded", "final_context": self.masking_service.mask_pii_data(current_context, self.pii_field_properties)},
                trace_depth=trace_depth,
                correlation_id=correlation_id
            ), db=self.db))
            
            return {"status": "FAILED", "workflow_id": self.workflow.workflow_id, "final_context": self.masking_service.mask_pii_data(current_context, self.pii_field_properties), "trace": self.execution_trace}

        # Mask the final output context before returning to prevent PII leakage, per Layer 6.
        masked_final_context = self.masking_service.mask_pii_data(current_context, self.pii_field_properties)

        self.execution_trace.append("--- Workflow execution finished ---")
        
        # --- BROADCAST COMPLETION EVENT ---
        trace_depth = current_context.get("__trace_depth__", 0) + 1
        correlation_id = current_context.get("__correlation_id__", f"CORR-{uuid.uuid4().hex[:12]}")
        asyncio.run(global_event_bus.broadcast(SystemEvent(
            event_type="WORKFLOW_COMPLETED",
            source_context=f"WorkflowExecutor:{self.workflow.workflow_id}",
            payload={"final_context": masked_final_context},
            trace_depth=trace_depth,
            correlation_id=correlation_id
        ), db=self.db))
        
        return {"status": "COMPLETED", "workflow_id": self.workflow.workflow_id, "final_context": masked_final_context, "trace": self.execution_trace}