import json
from typing import Dict, Any, List

class BusinessRulesEngine:
    """
    BUSINESS RULES ENGINE (BRE) CORE RUNTIME ENGINE
    Pillar: Logic-as-Data. Implements a parameter-driven computation matrix.
    Completely domain-agnostic; interprets rulesets generated by 'The Canvas OS'.
    """
    def __init__(self, rule_manifest_matrix: Dict[str, Any]):
        # This simulates loading the versioned policy configuration from the DB
        self.rule_id = rule_manifest_matrix.get("rule_id")
        self.version = rule_manifest_matrix.get("version")
        self.steps = rule_manifest_matrix.get("calculation_steps", [])

    def execute_logic(self, canonical_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Executes a sequence of mathematical operations or conditional filters
        on an incoming data stream based purely on the loaded ruleset data.
        """
        runtime_context = canonical_data.get("mapped_fields", {}).copy()
        execution_logs = []
        
        print(f"Executing Ruleset: {self.rule_id} ({self.version})")
        
        # Sequentially evaluate each node/step configured on the Canvas
        for step in self.steps:
            step_name = step.get("step_name")
            operation = step.get("operation") # e.g., MULTIPLY, PERCENTAGE_SPLIT, ALLOCATE
            source_field = step.get("source_field")
            target_field = step.get("target_field")
            parameter = step.get("parameter", 0.0)
            
            # Extract current running value from the data payload
            current_value = runtime_context.get(source_field, 0.0)
            
            if operation == "PERCENTAGE_SPLIT":
                # Compute a fractional allocation (e.g., managing tax cuts or fee shares)
                calculated_value = current_value * float(parameter)
                runtime_context[target_field] = calculated_value
                execution_logs.append(f"[{step_name}] Applied {parameter} split to {source_field}. Resulting target {target_field} = {calculated_value}")
                
            elif operation == "CAP_LIMIT":
                # Enforce a financial ceiling check limit
                calculated_value = min(current_value, float(parameter))
                runtime_context[target_field] = calculated_value
                execution_logs.append(f"[{step_name}] Enforced ceiling cap of {parameter} on {source_field}. Output = {calculated_value}")
                
            elif operation == "NET_BALANCE":
                # Basic differential logic block
                reducer_value = runtime_context.get(step.get("reducer_field"), 0.0)
                calculated_value = current_value - reducer_value
                runtime_context[target_field] = calculated_value
                execution_logs.append(f"[{step_name}] Subtracted {step.get('reducer_field')} from {source_field}. Final balance = {calculated_value}")

        return {
            "bre_metadata": {
                "rule_id": self.rule_id,
                "version": self.version,
                "execution_status": "COMPLETED_SUCCESSFULLY"
            },
            "final_calculated_state": runtime_context,
            "audit_trail_logs": execution_logs
        }


# Mock verification script to simulate active execution inside the workspace
if __name__ == "__main__":
    print("Initializing test run of the Business Rules Engine...")
    
    # 1. Simulate the data format produced by your Canonical Gateway
    mock_canonical_input = {
        "mapped_fields": {
            "iso_cb_field_name": 540000.00 # The raw ingestion amount
        }
    }
    
    # 2. Simulate the versioned ruleset matrix built visually in the BRE Panel
    # Note how no logic is coded below; it is entirely described as configuration metadata parameters.
    mock_bre_manifest = {
        "rule_id": "RULE-CALC-GLOBAL-V4",
        "version": "v4.2.1",
        "calculation_steps": [
            {
                "step_name": "Regulatory Fee Allocation",
                "operation": "PERCENTAGE_SPLIT",
                "source_field": "iso_cb_field_name",
                "parameter": "0.02", # 2% allocation rule
                "target_field": "allocated_processing_fees"
            },
            {
                "step_name": "Maximum Fee Safeguard Check",
                "operation": "CAP_LIMIT",
                "source_field": "allocated_processing_fees",
                "parameter": "8000.00", # Max cap limit rule
                "target_field": "final_sanitized_fees"
            },
            {
                "step_name": "Net Core Payout Settlement",
                "operation": "NET_BALANCE",
                "source_field": "iso_cb_field_name",
                "reducer_field": "final_sanitized_fees",
                "target_field": "net_disbursement_balance"
            }
        ]
    }
    
    # 3. Instantiate the engine and process the calculation run
    bre_instance = BusinessRulesEngine(mock_bre_manifest)
    calculation_result = bre_instance.execute_logic(mock_canonical_input)
    
    print("\n--- BRE RUNTIME PROCESSING COMPLETE ---")
    print(json.dumps(calculation_result, indent=2))
